/* ═══════════════════════════════════════
   REI DESIGNARY — tailwind.config.js
   ═══════════════════════════════════════ */

tailwind.config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container':           '#ff5f1f',
        'on-primary-container':        '#561700',
        'primary':                     '#ffb59c',
        'on-primary':                  '#5c1900',
        'primary-fixed':               '#ffdbcf',
        'primary-fixed-dim':           '#ffb59c',
        'on-primary-fixed':            '#390c00',
        'on-primary-fixed-variant':    '#832700',
        'inverse-primary':             '#ab3600',
        'secondary':                   '#c8c6c5',
        'on-secondary':                '#313030',
        'secondary-container':         '#4a4949',
        'on-secondary-container':      '#bab8b7',
        'secondary-fixed':             '#e5e2e1',
        'secondary-fixed-dim':         '#c8c6c5',
        'on-secondary-fixed':          '#1c1b1b',
        'on-secondary-fixed-variant':  '#474646',
        'tertiary':                    '#c8c6c5',
        'on-tertiary':                 '#313030',
        'tertiary-container':          '#959393',
        'on-tertiary-container':       '#2c2c2c',
        'tertiary-fixed':              '#e5e2e1',
        'tertiary-fixed-dim':          '#c8c6c5',
        'on-tertiary-fixed':           '#1c1b1b',
        'on-tertiary-fixed-variant':   '#474746',
        'background':                  '#121414',
        'on-background':               '#e2e2e2',
        'surface':                     '#121414',
        'on-surface':                  '#e2e2e2',
        'surface-variant':             '#333535',
        'on-surface-variant':          '#e3bfb3',
        'surface-dim':                 '#121414',
        'surface-bright':              '#37393a',
        'surface-tint':                '#ffb59c',
        'surface-container-lowest':    '#0c0f0f',
        'surface-container-low':       '#1a1c1c',
        'surface-container':           '#1e2020',
        'surface-container-high':      '#282a2b',
        'surface-container-highest':   '#333535',
        'inverse-surface':             '#e2e2e2',
        'inverse-on-surface':          '#2f3131',
        'outline':                     '#aa897f',
        'outline-variant':             '#5b4138',
        'error':                       '#ffb4ab',
        'on-error':                    '#690005',
        'error-container':             '#93000a',
        'on-error-container':          '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      spacing: {
        'margin-desktop': '80px',
        'margin-mobile':  '24px',
        'gutter':         '32px',
        'section-gap':    '128px',
        'base':           '8px',
        'phi':            '1.618',
      },
      fontFamily: {
        'display-lg':        ['Plus Jakarta Sans'],
        'display-lg-mobile': ['Plus Jakarta Sans'],
        'headline-xl':       ['Plus Jakarta Sans'],
        'headline-md':       ['Plus Jakarta Sans'],
        'body-lg':           ['Plus Jakarta Sans'],
        'body-md':           ['Plus Jakarta Sans'],
        'label-caps':        ['Plus Jakarta Sans'],
      },
      fontSize: {
        'display-lg':        ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
        'display-lg-mobile': ['48px', { lineHeight: '1.1', fontWeight: '800' }],
        'headline-xl':       ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md':       ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg':           ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md':           ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps':        ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
      },
    },
  },
};